# Data manipulation

In [51]:
import pandas as pd
import numpy as np

In [52]:
data = pd.read_csv('vehicles/vehicles.csv')
data.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [54]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

In [55]:
data.columns = ['Manufacturer','Model','Year','Displacement',
               'Cylinders','Transmission','Drivetrain',
               'Vehicle Class','Fuel Type','Fuel Barrels/Year',
               'City MPG','Highway MPG','Combined MPG',
               'CO2 Emission Grams/Mile','Fuel Cost/Year']

In [17]:
data.columns

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD',
       'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make',
       'model', 'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'guzzler',
       'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA',
       'evMotor', 'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr',
       'createdOn', 'modifiedOn', 'startStop', 'phevCity', 'phevHwy',
       'phevComb'],
      dtype='object')

In [56]:
data = data.rename(columns={'Manufacturer':'Make', 'Displacement' : 'Engine Displacement'})

In [57]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

In [58]:
column_order = ['Year','Make','Model','Vehicle Class',
               'Transmission','Drivetrain','Fuel Type',
               'Cylinders','Engine Displacement','Fuel Barrels/Year',
               'City MPG','Highway MPG','Combined MPG',
               'CO2 Emission Grams/Mile','Fuel Cost/Year']

In [59]:
data = data[column_order]

data.head()

,Year,Make,Model,Vehicle Class,Transmission,Drivetrain,Fuel Type,Cylinders,Engine Displacement,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,4.0,2.5,19.388824,18,17,17,522.764706,1950
1,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550
2,1985,AM General,Post Office DJ5 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,4.0,2.5,20.600625,16,17,16,555.437500,2100
3,1985,AM General,Post Office DJ8 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550
4,1987,ASC Incorporated,GNX,Midsize Cars,Automatic 4-spd,Rear-Wheel Drive,Premium,6.0,3.8,20.600625,14,21,16,555.437500,2550

In [60]:
#vamos a crear las etiquetas que queremos poner. Lo queremos clasificar en low, high...

In [61]:
mpg_labels = ['very low', 'low', 'moderate', 'high', 'very high']

In [62]:
bins = pd.cut(data['Combined MPG'], 5, labels=mpg_labels)

In [76]:
cutoffs = [7,14,20,23,35,80]
data['bins'] = pd.cut(data['Combined MPG'], cutoffs, labels = mpg_labels)

In [77]:
data.head()

,Year,Make,Model,Vehicle Class,Transmission,Drivetrain,Fuel Type,Cylinders,Engine Displacement,Fuel Barrels/Year,...,Average MPG,2-Wheel Drive,"2-Wheel Drive, Front",4-Wheel Drive,4-Wheel or All-Wheel Drive,All-Wheel Drive,Front-Wheel Drive,Part-time 4-Wheel Drive,Rear-Wheel Drive,bins
0,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,4.0,2.5,19.388824,...,14.75,1,0,0,0,0,0,0,0,low
1,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,6.0,4.2,25.354615,...,14.75,1,0,0,0,0,0,0,0,very low
2,1985,AM General,Post Office DJ5 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,4.0,2.5,20.600625,...,14.75,0,0,0,0,0,0,0,1,low
3,1985,AM General,Post Office DJ8 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,6.0,4.2,25.354615,...,14.75,0,0,0,0,0,0,0,1,very low
4,1987,ASC Incorporated,GNX,Midsize Cars,Automatic 4-spd,Rear-Wheel Drive,Premium,6.0,3.8,20.600625,...,16.00,0,0,0,0,0,0,0,1,low

In [82]:
data.loc[data['Transmission'].str.startswith('A'), 'TransType'] = 'Automatic'
data.loc[data['Transmission'].str.startswith('M'), 'TransType'] = 'Manual'

In [80]:
drivetrain = pd.get_dummies(data['Drivetrain'])
drivetrain.head()

,2-Wheel Drive,"2-Wheel Drive, Front",4-Wheel Drive,4-Wheel or All-Wheel Drive,All-Wheel Drive,Front-Wheel Drive,Part-time 4-Wheel Drive,Rear-Wheel Drive
0,1,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,1

In [67]:
#ALGO SUPER IMPORTANTE QUE VAMOS A USAR MUCHO: GROUP BY
#el GROUP BY agrupa variables. por ejemplo, para calcular el total del sueldo dividiendo por género harías group by género

In [68]:
avg_mpg = data.groupby('Make', as_index=False)['Combined MPG'].mean()

In [69]:
avg_mpg.columns = ['Make', 'Average MPG']

In [81]:
data.pivot_table(index='Make', value='Combined MPG', aggfunc=np.mean)

TypeError: pivot_table() got an unexpected keyword argument 'value'

In [71]:
#queremos hacer un merge de dos tables
data = pd.merge(data,avg_mpg, on='Make')

In [72]:
data.head()

,Year,Make,Model,Vehicle Class,Transmission,Drivetrain,Fuel Type,Cylinders,Engine Displacement,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Average MPG
0,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,4.0,2.5,19.388824,18,17,17,522.764706,1950,14.75
1,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550,14.75
2,1985,AM General,Post Office DJ5 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,4.0,2.5,20.600625,16,17,16,555.437500,2100,14.75
3,1985,AM General,Post Office DJ8 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550,14.75
4,1987,ASC Incorporated,GNX,Midsize Cars,Automatic 4-spd,Rear-Wheel Drive,Premium,6.0,3.8,20.600625,14,21,16,555.437500,2550,16.00

In [73]:
data = pd.concat([data,drivetrain], axis=1)

In [74]:
data.head()

,Year,Make,Model,Vehicle Class,Transmission,Drivetrain,Fuel Type,Cylinders,Engine Displacement,Fuel Barrels/Year,...,Fuel Cost/Year,Average MPG,2-Wheel Drive,"2-Wheel Drive, Front",4-Wheel Drive,4-Wheel or All-Wheel Drive,All-Wheel Drive,Front-Wheel Drive,Part-time 4-Wheel Drive,Rear-Wheel Drive
0,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,4.0,2.5,19.388824,...,1950,14.75,1,0,0,0,0,0,0,0
1,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,6.0,4.2,25.354615,...,2550,14.75,1,0,0,0,0,0,0,0
2,1985,AM General,Post Office DJ5 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,4.0,2.5,20.600625,...,2100,14.75,0,0,0,0,0,0,0,1
3,1985,AM General,Post Office DJ8 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,6.0,4.2,25.354615,...,2550,14.75,0,0,0,0,0,0,0,1
4,1987,ASC Incorporated,GNX,Midsize Cars,Automatic 4-spd,Rear-Wheel Drive,Premium,6.0,3.8,20.600625,...,2550,16.00,0,0,0,0,0,0,0,1

In [75]:
#melting data into long format

melted = pd.melt(data, id_vars= ['Year', 'Make', 'Model'],
                value_vars = ['City MPG', 'Highway MPG', 'Combined MPG'])
melted.head(10)

   Year              Make                Model  variable  value
0  1984        AM General    DJ Po Vehicle 2WD  City MPG     18
1  1984        AM General     FJ8c Post Office  City MPG     13
2  1985        AM General  Post Office DJ5 2WD  City MPG     16
3  1985        AM General  Post Office DJ8 2WD  City MPG     13
4  1987  ASC Incorporated                  GNX  City MPG     14
5  1997             Acura          2.2CL/3.0CL  City MPG     20
6  1997             Acura          2.2CL/3.0CL  City MPG     22
7  1997             Acura          2.2CL/3.0CL  City MPG     18
8  1998             Acura          2.3CL/3.0CL  City MPG     19
9  1998             Acura          2.3CL/3.0CL  City MPG     21